cinst VisualStudio2013Ultimate -InstallArguments "Blend LightSwitch VC_MFC_Libraries OfficeDeveloperTools SQL WebTools Win8SDK SilverLight_Developer_Kit WindowsPhone80"
cinst Office365HomePremium
cinst resharper
cinst MsSqlServer2014Express
cinst MsSqlServerManagementStudio2014Express
